import { Montserrat } from 'next/font/google';
import "./globals.css";

export const metadata = {
  title: "Grupo Moreira",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800','900'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body
        className={montserrat.className}
      >
        {children}
      </body>
    </html>
  );
}
